-- =================================================================================
-- T-SQL SCRIPT FOR IDENTITY RESEED
-- Target Database: SMDB_FINAL
-- =================================================================================

USE SMDB_FINAL;
GO

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;

-- =================================================================================
-- BIẾN ĐIỀU KHIỂN CHÍNH (MASTER CONTROLLER FLAG)
-- =================================================================================
-- 0 = DRY-RUN MODE: Chỉ hiển thị lệnh DBCC CHECKIDENT dự kiến chạy, không thay đổi.
-- 1 = EXECUTE MODE: Thực thi DBCC CHECKIDENT trong TRANSACTION (Có rollback).
-- =================================================================================
DECLARE @DoExecute BIT = 0;

PRINT '=================================================================================';
PRINT 'KỊCH BẢN KHỞI TẠO LẠI SEED IDENTITY SAU CLEANUP (SMDB_FINAL)';
PRINT 'Trạng thái chạy thử nghiệm (DoExecute) = ' + CAST(@DoExecute AS VARCHAR(1));
PRINT '=================================================================================';

-- Bảng tạm lưu trữ thông tin preview
IF OBJECT_ID('tempdb..#ReseedPreview') IS NOT NULL DROP TABLE #ReseedPreview;
CREATE TABLE #ReseedPreview (
    TableName NVARCHAR(128),
    ColumnName NVARCHAR(128),
    MaxId BIGINT,
    CurrentSeedVal BIGINT,
    NextExpectedId BIGINT,
    ProposedCommand NVARCHAR(255)
);

-- Khai báo con trỏ duyệt qua tất cả cột Identity của các bảng người dùng
DECLARE @TableName NVARCHAR(128);
DECLARE @ColumnName NVARCHAR(128);
DECLARE @SQL NVARCHAR(MAX);
DECLARE @MaxId BIGINT;
DECLARE @CurrentSeed BIGINT;

DECLARE IdCursor CURSOR FOR
SELECT t.name AS TableName, c.name AS ColumnName
FROM sys.identity_columns c
JOIN sys.tables t ON c.object_id = t.object_id
WHERE t.is_ms_shipped = 0
  AND t.name <> 'sysdiagrams';

OPEN IdCursor;
FETCH NEXT FROM IdCursor INTO @TableName, @ColumnName;

WHILE @@FETCH_STATUS = 0
BEGIN
    -- 1. Lấy MAX(id) hiện tại
    SET @SQL = N'SELECT @MaxId_Out = ISNULL(MAX([' + @ColumnName + ']), 0) FROM [' + @TableName + ']';
    EXEC sp_executesql @SQL, N'@MaxId_Out BIGINT OUTPUT', @MaxId_Out = @MaxId OUTPUT;

    -- 2. Lấy giá trị seed hiện tại từ metadata
    SET @CurrentSeed = CAST(IDENT_CURRENT(@TableName) AS BIGINT);

    -- 3. Xác định giá trị reseed và giá trị dự kiến tiếp theo
    DECLARE @ReseedValue BIGINT;
    DECLARE @NextExpected BIGINT;

    IF @MaxId = 0
    BEGIN
        -- Bảng rỗng: reseed về 0 để giá trị insert tiếp theo là 1
        SET @ReseedValue = 0;
        SET @NextExpected = 1;
    END
    ELSE
    BEGIN
        -- Bảng có dữ liệu: reseed về MAX(id) để giá trị tiếp theo là MAX(id) + 1
        SET @ReseedValue = @MaxId;
        SET @NextExpected = @MaxId + 1;
    END

    -- 4. Tạo lệnh Proposed Command
    DECLARE @Cmd NVARCHAR(255);
    SET @Cmd = N'DBCC CHECKIDENT (''' + @TableName + ''', RESEED, ' + CAST(@ReseedValue AS NVARCHAR(20)) + N');';

    -- Đưa vào bảng preview
    INSERT INTO #ReseedPreview (TableName, ColumnName, MaxId, CurrentSeedVal, NextExpectedId, ProposedCommand)
    VALUES (@TableName, @ColumnName, @MaxId, @CurrentSeed, @NextExpected, @Cmd);

    FETCH NEXT FROM IdCursor INTO @TableName, @ColumnName;
END;

CLOSE IdCursor;
DEALLOCATE IdCursor;

-- =================================================================================
-- 1. DRY-RUN MODE: HIỂN THỊ DANH SÁCH BẢNG & LỆNH DỰ KIẾN
-- =================================================================================
IF @DoExecute = 0
BEGIN
    PRINT '--- DANH SÁCH CÁC BẢNG SẼ THỰC HIỆN RESEED IDENTITY ---';
    SELECT TableName,
           ColumnName AS [Identity_Column],
           MaxId AS [MAX_ID_In_Table],
           CurrentSeedVal AS [Current_Identity_Value],
           NextExpectedId AS [Next_Autogenerated_ID],
           ProposedCommand AS [Suggested_DBCC_Command]
    FROM #ReseedPreview
    ORDER BY TableName;

    PRINT '=================================================================================';
    PRINT 'DRY-RUN HOÀN TẤT. KHÔNG CÓ THAY ĐỔI IDENTITY SEED NÀO ĐƯỢC THỰC THI.';
    PRINT '=================================================================================';
END
-- =================================================================================
-- 2. EXECUTE MODE: THỰC THI CHẠY THẬT TRONG TRANSACTION
-- =================================================================================
ELSE
BEGIN
    PRINT '=================================================================================';
    PRINT 'ĐANG THỰC THI KHỞI TẠO LẠI SEED IDENTITY TRONG TRANSACTION...';
    PRINT '=================================================================================';

    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @ExecTableName NVARCHAR(128);
        DECLARE @ExecCommand NVARCHAR(255);

        DECLARE ExecCursor CURSOR FOR
        SELECT TableName, ProposedCommand FROM #ReseedPreview;

        OPEN ExecCursor;
        FETCH NEXT FROM ExecCursor INTO @ExecTableName, @ExecCommand;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            PRINT '  - Đang chạy Reseed cho bảng [' + @ExecTableName + ']...';
            -- Chạy lệnh DBCC CHECKIDENT động
            EXEC sp_executesql @ExecCommand;
            
            FETCH NEXT FROM ExecCursor INTO @ExecTableName, @ExecCommand;
        END;

        CLOSE ExecCursor;
        DEALLOCATE ExecCursor;

        COMMIT TRANSACTION;
        PRINT '=================================================================================';
        PRINT 'TRANSACTION ĐÃ ĐƯỢC COMMIT THÀNH CÔNG. TẤT CẢ IDENTITY SEED ĐÃ ĐƯỢC KHỞI TẠO LẠI.';
        PRINT '=================================================================================';

        -- SELECT Báo cáo kết quả kiểm tra lại seed mới
        PRINT '--- BÁO CÁO CẬP NHẬT TRẠNG THÁI SEED SAU KHI THỰC THI ---';
        SELECT TableName,
               ColumnName AS [Identity_Column],
               MaxId AS [MAX_ID_In_Table],
               CAST(IDENT_CURRENT(TableName) AS BIGINT) AS [New_Current_Identity_Value]
        FROM #ReseedPreview
        ORDER BY TableName;

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
        BEGIN
            ROLLBACK TRANSACTION;
            PRINT '=================================================================================';
            PRINT 'GẶP LỖI TRONG QUÁ TRÌNH THỰC THI. TRANSACTION ĐÃ ĐƯỢC ROLLBACK.';
            PRINT 'Chi tiết lỗi: ' + ERROR_MESSAGE();
            PRINT '=================================================================================';
        END
    END CATCH
END
GO
