-- V1.15: Add GHN shipping fields to HoaDon table (idempotent - safe to run if columns already exist)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HoaDon' AND COLUMN_NAME = 'ghn_order_code')
    ALTER TABLE HoaDon ADD ghn_order_code NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HoaDon' AND COLUMN_NAME = 'ghn_status')
    ALTER TABLE HoaDon ADD ghn_status NVARCHAR(100) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HoaDon' AND COLUMN_NAME = 'ghn_to_district_id')
    ALTER TABLE HoaDon ADD ghn_to_district_id INT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HoaDon' AND COLUMN_NAME = 'ghn_to_ward_code')
    ALTER TABLE HoaDon ADD ghn_to_ward_code NVARCHAR(20) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HoaDon' AND COLUMN_NAME = 'phi_ship')
    ALTER TABLE HoaDon ADD phi_ship DECIMAL(18,2) NULL;
