-- Migration V3: Add thuoc_tinh column to DanhMuc table
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DanhMuc' AND COLUMN_NAME = 'mau_sac_mac_dinh')
BEGIN
    ALTER TABLE DanhMuc DROP COLUMN mau_sac_mac_dinh;
END;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DanhMuc' AND COLUMN_NAME = 'kich_thuoc_mac_dinh')
BEGIN
    ALTER TABLE DanhMuc DROP COLUMN kich_thuoc_mac_dinh;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DanhMuc' AND COLUMN_NAME = 'thuoc_tinh')
BEGIN
    ALTER TABLE DanhMuc ADD thuoc_tinh NVARCHAR(1000) NULL;
END;
